supplement for community members
minskpython/minskpython.github.io pull request #28
Opened 2018-11-13 22:00 UTC by vir-mir

2019-01-13 12:50 UTC, shurph requested changes
Хорошее дополнение про _«помогают с оформлением докладов»_.
Думаю, можно даже здесь написать _«, помогают с оформлением докладов и другими способами вносят вклад в сообщество»_. @vir-mir, сделаешь?

А в дальнейшем нужно будет добавить отдельный раздел, или даже документ, который будет отвечать на вопрос «Как я могу помочь сообщесту?». Но тут уже нужно уточнять у @ttsygan и @nott , какая помощь нужна сейчас (и какая — нужна всегда).

2019-01-13 12:50 UTC, miksask commented on README.md
> +- Члены сообщества — активно голосуют за темы докладов лайками и комментами, вносят конструктивную критику, выражают своё одобрение и похвалу, помогают с оформлением докладов
А такая практика есть сейчас? Я про «помогают с оформлением докладов».

2019-02-23 12:51 UTC, shurph commented
Оставим пока так, как есть. В ближайшее время, как я понимаю, планируется значительное изменение этого документа. Возможно, всё будет совсем иначе :-)

2019-02-23 12:51 UTC, merged

2019-02-26 18:21 UTC, vir-mir commented
Да, сори, пока что времени вообще нет